apiVersion: apps/v1
kind: Deployment
metadata:
  name: csrvbot
  namespace: csrvbot
spec:
  selector:
    matchLabels:
      app: csrvbot
  template:
    metadata:
      labels:
        app: csrvbot
    spec:
      imagePullSecrets:
        - name: craftserve-registry
      containers:
        - name: csrvbot
          tty: true
          stdin: true
          image: localhost:30105/csrvbot/csrvbot:stable
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          imagePullPolicy: Always
          volumeMounts:
            - name: csrvbot-config
              mountPath: "/app/config.json"
              subPath: config.json
              readOnly: true
      volumes:
        - name: csrvbot-config
          secret:
            secretName: csrvbot-config
            optional: false